version: "2"
services:
  app:
    build: ./app/
    restart: on-failure
    links:
      - db
    ports:
      - "8000:8000"
    networks:
      - main-network
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: poop
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d/:ro
    networks:
      - main-network
  nginx:
    image: jwuebblz/league_kda_angular:latest
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - main-network
networks:
  main-network:
    driver: bridge
