version: "2"
services:
  app:
    # Builds the dockerfile in the ./app/ directory.
    build: ./app/
    restart: on-failure
    links:
      - db
    # Maps my machine's port 5000 to the containers port 5000.
    ports:
      - "8000:8000"
    networks:
      - main-network
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: poop
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d/:ro
    networks:
      - main-network
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - main-network
networks:
  main-network:
    driver: bridge
