version: "2"
services:
  app:
    build: ./app/
    links:
      - db
    ports:
      - "5000:5000"
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: poop
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d/:ro